name: kodi
title: Kodi
base: core24
adopt-info: kodi
summary: An award-winning free and open source home theater/media center software
description: |
  Kodi is an award-winning free and open source software media player and
  entertainment hub for digital media. Available as a native application for
  Android, Linux, BSD, macOS, iOS, tvOS and Windows operating systems, Kodi runs
  on most common processor architectures.

  Created in 2003 by a group of like minded programmers, Kodi is a non-profit
  project run by the XBMC Foundation and developed by volunteers located around
  the world. More than 500 software developers have contributed to Kodi to date,
  and 100-plus translators have worked to expand its reach, making it available
  in more than 70 languages.

  While Kodi functions very well as a standard media player application for your
  computer, it has been designed to be the perfect companion for your HTPC. With
  its beautiful interface and powerful skinning engine, Kodi feels very natural
  to use from the couch with a remote control and is the ideal solution for your
  home theater.

  ---

  \#\# Interfaces:
  - `gpu-2404`
    Provides the userspace GPU drivers, enabling rendering and video decoding
    acceleration. See [The gpu-2404 snap interface](https://mir-server.io/docs/the-gpu-2404-snap-interface)
    for more information.
    This will normally be connected to the [`mesa-2404`](https://snapcraft.io/mesa-2404/)
    snap, serving all open source drivers and Nvidia userspace from the host
    system, where possible.

icon: snap/gui/kodi.svg
website: https://kodi.tv/
donation:
- https://patreon.com/Teamkodi
- https://liberapay.com/teamkodi
- https://kodi.tv/contribute/donate
source-code:
- https://github.com/Saviq/kodi.snap
- https://github.com/xbmc/xbmc
issues:
- https://github.com/Saviq/kodi.snap/issues
- https://github.com/xbmc/xbmc/issues
contact:
- https://github.com/Saviq/kodi.snap
license: GPL-2.0-or-later

grade: devel
confinement: devmode

layout:
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

parts:
  displayinfo:
    source: https://gitlab.freedesktop.org/emersion/libdisplay-info.git
    source-tag: 0.2.0
    source-depth: 1
    build-packages:
    - hwdata
    - meson
    plugin: meson
    meson-parameters:
    - --prefix=/usr

  embed-libs:
    plugin: nil
    build-packages:
    - curl
    override-pull: |
      curl --location --output \
        ${CRAFT_PART_SRC}/libdvdcss.tar.gz \
        https://github.com/xbmc/libdvdcss/archive/1.4.3-Next-Omega-Alpha3.tar.gz
      curl --location --output \
        ${CRAFT_PART_SRC}/libdvdnav.tar.gz \
        https://github.com/xbmc/libdvdnav/archive/6.1.1-Next-Nexus-Alpha2-2.tar.gz
      curl --location --output \
        ${CRAFT_PART_SRC}/libdvdread.tar.gz \
        https://github.com/xbmc/libdvdread/archive/6.1.3-Next-Nexus-Alpha2-2.tar.gz

  kodi:
    after: [displayinfo, embed-libs]
    source: https://github.com/xbmc/xbmc.git
    source-tag: 21.1-Omega
    source-depth: 1

    build-packages:
    # from https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md
    - debhelper
    - autoconf
    - automake
    - autopoint
    - gettext
    - autotools-dev
    - cmake
    - curl
    - default-jre
    - gawk
    - gcc
    - gdc
    - gperf
    - libasound2-dev
    - libass-dev
    - libavahi-client-dev
    - libavahi-common-dev
    - libbluetooth-dev
    - libbluray-dev
    - libbz2-dev
    - libcdio-dev
    - libp8-platform-dev
    - libcrossguid-dev
    - libcurl4-openssl-dev
    - libcwiid-dev
    - libdbus-1-dev
    - libdrm-dev
    - libegl1-mesa-dev
    - libenca-dev
    - libflac-dev
    - libfmt-dev
    - libfontconfig-dev
    - libfreetype-dev
    - libfribidi-dev
    - libfstrcmp-dev
    - libgcrypt20-dev
    - libgif-dev
    - libgles2-mesa-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libgnutls28-dev
    - libgpg-error-dev
    - libgtest-dev
    - libiso9660-dev
    - libjpeg-dev
    - libkissfft-dev
    - liblcms2-dev
    - libltdl-dev
    - liblzo2-dev
    - libmicrohttpd-dev
    - libmysqlclient-dev
    - libnfs-dev
    - libogg-dev
    - libpcre2-dev
    - libplist-dev
    - libpng-dev
    - libpulse-dev
    - libshairplay-dev
    - libsmbclient-dev
    - libspdlog-dev
    - libsqlite3-dev
    - libssl-dev
    - libtag1-dev
    - libtiff5-dev
    - libtinyxml-dev
    - libtinyxml2-dev
    - libtool
    - libudev-dev
    - libunistring-dev
    - libva-dev
    - libvdpau-dev
    - libvorbis-dev
    - libxmu-dev
    - libxrandr-dev
    - libxslt1-dev
    - libxt-dev
    - lsb-release
    - meson
    - nasm
    - ninja-build
    - python3-dev
    - python3-pil
    - python3-pip
    - rapidjson-dev
    - swig
    - unzip
    - uuid-dev
    - zip
    - zlib1g-dev

    ## flatbuffers
    - libflatbuffers-dev

    ## wayland
    - libglew-dev
    - libwayland-dev
    - libxkbcommon-dev
    - waylandpp-dev
    - wayland-protocols

    ## optional
    - libcap-dev
    - libsndio-dev

    # libav
    - libavcodec-dev
    - libavfilter-dev
    - libavformat-dev
    - libswscale-dev
    - libpostproc-dev

    # gbm support
    - libgbm-dev
    - libinput-dev

    # additional
    - libcec-dev
    - libcdio++-dev
    - libdav1d-dev
    - libiso9660++-dev
    - liblirc-dev
    - libmdnsd-dev
    - libpcre3-dev
    - libpipewire-0.3-dev

    # build tools
    - lld
    - ccache

    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DCORE_PLATFORM_NAME="x11 wayland gbm"
    - -DAPP_RENDER_SYSTEM=gl
    - -DADDONS_CONFIGURE_AT_STARTUP=OFF
    - -DVERBOSE=1

    - -DENABLE_AIRTUNES=ON
    - -DENABLE_ALSA=ON
    - -DENABLE_ATOMIC=ON
    - -DENABLE_AVAHI=ON
    - -DENABLE_AVX2=ON
    - -DENABLE_AVX=ON
    - -DENABLE_BLUETOOTH=ON
    - -DENABLE_BLURAY=ON
    - -DENABLE_CAP=ON
    - -DENABLE_CEC=ON
    - -DENABLE_DAV1D=ON
    - -DENABLE_DBUS=ON
    - -DENABLE_DEBUGFISSION=ON
    - -DENABLE_DVDCSS=ON
    - -DENABLE_EGL=ON
    - -DENABLE_EVENTCLIENTS=ON
    - -DENABLE_GBM=ON
    - -DENABLE_GLX=ON
    - -DENABLE_ISO9660PP=ON
    - -DENABLE_LCMS2=ON
    - -DENABLE_LIBDISPLAYINFO=ON
    - -DENABLE_LIBDRM=ON
    - -DENABLE_LIBINPUT=ON
    - -DENABLE_LIRCCLIENT=ON
    - -DENABLE_MICROHTTPD=ON
    - -DENABLE_MYSQLCLIENT=ON
    - -DENABLE_NFS=ON
    - -DENABLE_OPENGL=ON
    - -DENABLE_OPTICAL=ON
    - -DENABLE_PIPEWIRE=ON
    - -DENABLE_PLIST=ON
    - -DENABLE_PULSEAUDIO=ON
    - -DENABLE_PYTHON=ON
    - -DENABLE_SMBCLIENT=ON
    - -DENABLE_SNDIO=ON
    - -DENABLE_UDEV=ON
    - -DENABLE_UDFREAD=ON
    - -DENABLE_UPNP=ON
    - -DENABLE_VAAPI=ON
    - -DENABLE_VDPAU=ON
    - -DENABLE_WAYLANDPP=ON
    - -DENABLE_WAYLANDPROTOCOLS=ON
    - -DENABLE_X=ON
    - -DENABLE_XKBCOMMON=ON
    - -DENABLE_XRANDR=ON
    - -DENABLE_XSLT=ON

    - -DENABLE_CCACHE=ON
    - -DENABLE_LLD=ON

    - -DENABLE_CLANGTIDY=OFF
    - -DENABLE_CPPCHECK=OFF
    - -DENABLE_GOLD=OFF
    - -DENABLE_INCLUDEWHATYOUUSE=OFF
    - -DENABLE_MOLD=OFF
    - -DENABLE_TESTING=OFF

    - -DENABLE_INTERNAL_CEC=OFF
    - -DENABLE_INTERNAL_CROSSGUID=OFF
    - -DENABLE_INTERNAL_DAV1D=OFF
    - -DENABLE_INTERNAL_FFMPEG=OFF
    - -DENABLE_INTERNAL_FLATBUFFERS=OFF
    - -DENABLE_INTERNAL_FMT=OFF
    - -DENABLE_INTERNAL_FSTRCMP=OFF
    - -DENABLE_INTERNAL_GTEST=OFF
    - -DENABLE_INTERNAL_KISSFFT=OFF
    - -DENABLE_INTERNAL_NFS=OFF
    - -DENABLE_INTERNAL_PCRE=OFF
    - -DENABLE_INTERNAL_RapidJSON=OFF
    - -DENABLE_INTERNAL_SPDLOG=OFF
    - -DENABLE_INTERNAL_TAGLIB=OFF
    - -DENABLE_INTERNAL_UDFREAD=OFF

    - -DLIBDVDCSS_URL=${CRAFT_PART_SRC}/../../embed-libs/src/libdvdcss.tar.gz
    - -DLIBDVDCSS_HASH=SHA512=1506c83fb665d9deff8352e3b08d8c691e91c57d89bcdd32bd3187d3dd973563d394754060a48b3e6497cb30e774e94cb8b727ca8cc08287e2d604177072a424
    - -DLIBDVDNAV_URL=${CRAFT_PART_SRC}/../../embed-libs/src/libdvdnav.tar.gz
    - -DLIBDVDNAV_HASH=SHA512=51e6fc033121241354a5f0b3fc9a430577ae3ff6bb7f31445aa548ef4893037fb80eea3b2c6774c81e9ebaf9c45e9b490c98c2c65eb38f9f7daba84b236f7e1d
    - -DLIBDVDREAD_URL=${CRAFT_PART_SRC}/../../embed-libs/src/libdvdread.tar.gz
    - -DLIBDVDREAD_HASH=SHA512=629a41157d07b8ec0ea1fe89ae5ec48f63047472a862782b805c531ae31a0376fc4dc15175f8280c3ef91d7fa977bacebb1b51232640034a34bab2293210fc5e

    stage-packages:
    - libaom3
    - libasound2t64
    - libasound2-plugins
    - libass9
    - libasyncns0
    - libavahi-client3
    - libavahi-common3
    - libavcodec60
    - libavfilter9
    - libavformat60
    - libavutil58
    - libblas3
    - libbluetooth3
    - libbluray2
    - libbs2b0
    - libcairo-gobject2
    - libcairo2
    - libcdio19t64
    - libcec6
    - libchromaprint1
    - libcjson1
    - libcodec2-1.2
    - libcrossguid0
    - libcurl4t64
    - libdatrie1
    - libdav1d7
    - libegl1
    - libfftw3-double3
    - libflac12t64
    - libflite1
    - libfmt9
    - libfontconfig1
    - libfribidi0
    - libfstrcmp0
    - libgdk-pixbuf-2.0-0
    - libgfortran5
    - libgif7
    - libglvnd0
    - libgme0
    - libgomp1
    - libgraphite2-3
    - libgsm1
    - libgudev-1.0-0
    - libharfbuzz0b
    - libhwy1t64
    - libicu74
    - libinput10
    - libiso9660-11t64
    - libjansson4
    - libjpeg-turbo8
    - libjxl0.7
    - libkissfft-float131
    - liblapack3
    - liblcms2-2
    - libldap2
    - libldb2
    - liblilv-0-0
    - liblirc-client0t64
    - libmbedcrypto7t64
    - libmicrohttpd12t64
    - libmp3lame0
    - libmpg123-0t64
    - libmtdev1t64
    - libmysofa1
    - libmysqlclient21
    - libnfs14
    - libnghttp2-14
    - libnorm1t64
    - libnuma1
    - libogg0
    - libopenjp2-7
    - libopenmpt0t64
    - libopus0
    - libp8-platform2
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpcre3
    - libpgm-5.3-0t64
    - libpipewire-0.3-0t64
    - libpipewire-0.3-modules
    - libpixman-1-0
    - libplacebo338
    - libplist-2.0-4
    - libpocketsphinx3
    - libpostproc57
    - libpsl5t64
    - libpulse0
    - libpython3.12t64
    - librabbitmq4
    - librav1e0
    - librav1e0
    - librist4
    - librsvg2-2
    - librtmp1
    - librubberband2
    - libsamplerate0
    - libsasl2-2
    - libserd-0-0
    - libshairplay0
    - libsharpyuv0
    - libshine3
    - libsmbclient0
    - libsnappy1v5
    - libsndfile1
    - libsndio7.0
    - libsodium23
    - libsord-0-0
    - libsoxr0
    - libspdlog1.12
    - libspeex1
    - libsphinxbase3t64
    - libsratom-0-0
    - libsrt1.5-gnutls
    - libssh-4
    - libssh-gcrypt-4
    - libsvtav1enc1d1
    - libswresample4
    - libswscale7
    - libtag1v5-vanilla
    - libtalloc2
    - libtdb1
    - libtevent0t64
    - libthai0
    - libtinyxml2-10
    - libtinyxml2.6.2v5
    - libtwolame0
    - libudfread0
    - libunibreak5
    - libvidstab1.1
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libvpl2
    - libvpx9
    - libwacom9
    - libcwiid1t64
    - libwayland-client++1
    - libwayland-cursor++1
    - libwayland-cursor0
    - libwayland-egl++1
    - libwbclient0
    - libwebp7
    - libwebpmux3
    - libx11-6
    - libx11-xcb1
    - libx264-164
    - libx265-199
    - libxau6
    - libxcb-dri3-0
    - libxcb-randr0
    - libxcb-render0
    - libxcb1
    - libxdmcp6
    - libxml2
    - libxrandr2
    - libxrender1
    - libxslt1.1
    - libxvidcore4
    - libzimg2
    - libzix-0-0
    - libzmq5
    - libzvbi0t64
    - ocl-icd-libopencl1
    - pipewire-bin
    - samba-libs
    - xkb-data
    override-stage: |
      craftctl default
      craftctl set version=$( git -C ${CRAFT_PART_SRC} describe --tags )
      awk -i inplace -f ${CRAFT_PROJECT_DIR}/snap/local/alsa.conf.awk ${CRAFT_STAGE}/usr/share/alsa/alsa.conf
      sed -i 's|Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/kodi.svg|g' ${CRAFT_STAGE}/usr/share/applications/kodi.desktop

    prime:
    - -usr/lib/*/libcjson_utils.so*
    - -usr/lib/*/libdcerpc-server.so*
    - -usr/lib/*/libdconf.so*
    - -usr/lib/*/libexslt.so*
    - -usr/lib/*/libfftw3_omp.so*
    - -usr/lib/*/libfftw3_threads.so*
    - -usr/lib/*/libflite_cmu_grapheme_lang.so*
    - -usr/lib/*/libflite_cmu_grapheme_lex.so*
    - -usr/lib/*/libflite_cmu_indic_lang.so*
    - -usr/lib/*/libflite_cmu_indic_lex.so*
    - -usr/lib/*/libflite_cmu_time_awb.so*
    - -usr/lib/*/libhwy_contrib.so*
    - -usr/lib/*/libhwy_test.so*
    - -usr/lib/*/libjacknet.so*
    - -usr/lib/*/libjackserver.so*
    - -usr/lib/*/libnetapi.so*
    - -usr/lib/*/libpcreposix.so*
    - -usr/lib/*/libsphinxad.so*
    - -usr/lib/*/libtheora.so*
    - -usr/lib/*/libunwind-coredump.so*
    - -usr/lib/*/libunwind-ptrace.so*
    - -usr/lib/*/libunwind-x86_64.so*
    - -usr/lib/*/libwayland-client-unstable++.so*
    - -usr/lib/*/libzvbi-chains.so*
    organize:
      usr/lib/*/blas/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/
      usr/lib/*/lapack/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/
      usr/lib/*/pulseaudio/*: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/

  glue:
    source: glue
    plugin: nil
    override-build: |
      sed "s/%ARCH_TRIPLET%/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/g" ${CRAFT_PART_SRC}/kodi.wrapper.in > ${CRAFT_PART_INSTALL}/kodi.wrapper
      chmod +x ${CRAFT_PART_INSTALL}/kodi.wrapper

  gpu-2404:
    after: [kodi]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper

environment:
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
  XDG_CACHE_HOME:  ${SNAP_USER_COMMON}/.cache
  XDG_CONFIG_HOME: ${SNAP_USER_DATA}/.config
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg
  XDG_DATA_DIRS:   ${SNAP}/usr/share
  # ALSA
  ALSA_CONFIG_DIR: ${SNAP}/usr/share/alsa
  ALSA_PLUGIN_DIR: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/alsa-lib
  # Pipewire
  PIPEWIRE_CONFIG_DIR: ${SNAP}/usr/share/pipewire
  PIPEWIRE_MODULE_DIR: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pipewire-0.3
  SPA_PLUGIN_DIR: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/spa-0.2
  # Kodi
  KODI_HOME: ${SNAP}/usr/share/kodi
  KODI_BIN_HOME: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/kodi

apps:
  kodi:
    desktop: usr/share/applications/kodi.desktop
    plugs:
    - gpu-2404
    environment:
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
      PIPEWIRE_RUNTIME_DIR: $XDG_RUNTIME_DIR/..
    command-chain:
    - bin/gpu-2404-wrapper
    - kodi.wrapper
    command: usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/kodi/kodi.bin
